# For more details, see https://containers.dev/guide/dependabot
version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
